package:
  name: clasv
  version: "0.1.0"

source:
  path: .

build:
  noarch: python
  script:
    - echo "Contents of work directory:"
    - ls -la $SRC_DIR
    - set +e
    - chmod +x $HOME/.local/bin/nextclade
    - "{{ PYTHON }} -m pip install --no-cache-dir snakemake==7.15.3"
    - "{{ PYTHON }} -m pip install ."
    - "{{ PYTHON }} -c 'from CLASV.install_nextclade import install_nextclade; install_nextclade()'"
requirements:
  build:
    - python >=3.6
    - pip
    - curl
  run:
    - python >=3.6
    - biopython
    - pandas
    - matplotlib
    - scikit-learn

extra:
  pip:
    - snakemake
  channels:
    - bioconda
    - conda-forge

about:
  home: https://github.com/JoiRichi/CLASV/commits?author=JoiRichi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "CLASV: Lassa Virus Analysis Pipeline"
  description: |
    CLASV is a pipeline for analyzing Lassa virus datasets using advanced computational techniques.
  dev_url: https://github.com/JoiRichi/CLASV

extra:
  recipe-maintainers:
    - JoiRichi
