figures_title: LASV Lineage Prediction
filter:
  min_length: 500
include_fastq: false
model: /Users/joirichi/clasv_bioconda/CLASV/CLASV/config/RF_LASV_lineage_n100_aa.joblib
output: /Users/joirichi/Downloads/Data_Science/Bioinformatics/clasv_test/results
raw_seq_folder: /Users/joirichi/Downloads/Data_Science/Bioinformatics/clasv_test
recursive: false
reference: /Users/joirichi/clasv_bioconda/CLASV/CLASV/config/NC_004296.fasta
