figures_title: Lineages Prediction
filter:
  min_length: 500
model: config/RF_LASV_lineage_n1000_aa.joblib
output:
  predictions: files/predictions
  results: files/results
  visuals: files/visuals
raw_seq_folder: CLASV
